version: '3.4'

services:
  mch.api:
    image: ${DOCKER_REGISTRY-}mchapi
    build:
      context: .
      dockerfile: MCH.API/Dockerfile
    ports:
      - 5000:80
      
  mch.ml:
    image: ${DOCKER_REGISTRY-}mchml
    build:
      context: ./MCH.ML
      dockerfile: Dockerfile
    ports:
      - 5001:8000
   
  mch.parser:
    image: ${DOCKER_REGISTRY-}mchparser
    build:
      context: .
      dockerfile: MCH.Parser/Dockerfile
      
  nginx:
    image: nginx:latest
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 4201:80
     
 